### PR TITLE
Gatsby Plugin Initial Build. [Sends data directly to Rudderstack from Gatsby Website]

### PR DESCRIPTION
**Pull request by cwray-tech**
This is the initial pull request for the issue: https://github.com/rudderlabs/rudder-server/issues/655

This is a Gatsby plugin that is ready for better in-depth testing. Once it has been thoroughly tested, it can also be published on NPM and Yarn.

The example directory is a Gatsby website that is set up. Follow the Readme instructions to run the website on your local machine and test!

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
@cwray-tech I can't get the example project to run in develop or build right now. A couple of issues, 1) There are 2 PagesQuery calls, 2) it cannot find module './src/templates/dog-template.js'.

I'll continue testing on this tomorrow.

- Gavin

**Comment by cwray-tech** [comment]
@thtmnisamnstr

I was getting those errors, but what I had to do is run Gatsby clean and then Gatsby develop and it worked, but I will remove that directory and create a fresh site. It’s really weird though that it’s giving you that error.

Also can you point me to where I am calling the pages analytics twice?

Just to let you know the Gatsby API files in the root directory are generated with babel. The only 2 files that I wrote code in are in the src directory.

**Comment by thtmnisamnstr** [comment]
@cwray-tech  If I get the error again tomorrow, I'll let you know where. I'm pretty sure the double call wasn't the issue though. I think it was the missing template.

**Comment by cwray-tech** [comment]
https://www.loom.com/share/f377f968bf634fcab63498c03f247d43

I updated the example website.

**Review by thtmnisamnstr — APPROVED** [review]
This all seems to be working. I may update the readme in the future, but that's not blocking. I'm merging this PR.

- Gavin

**Pull request merged**
